import React, {useState, useEffect, useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Search, Heart, Plus, ArrowUpRight, ArrowRight, BookOpen, Laptop, Armchair, Grid2X2, SlidersHorizontal, X, MapPin, Repeat2, Leaf, ShieldCheck, Check, ShoppingBag, Mail} from 'lucide-react';
import './styles.css';
const categories=[['All finds',Grid2X2],['Textbooks',BookOpen],['Tech',Laptop],['Dorm essentials',Armchair]];
const seed=[
{id:'1',title:'Calculus: Early Transcendentals',category:'Textbooks',price:850,condition:'Like new',seller:'Maya',campus:'Addis Ababa University',description:'Sample listing. A clean textbook with a few pencil notes. Perfect for first-year calculus.',art:'book',color:'#d4e5dd',label:'CALCULUS',created:6},
{id:'2',title:'Wireless noise-canceling headphones',category:'Tech',price:2400,condition:'Good',seller:'Daniel',campus:'Addis Ababa University',description:'Sample listing. Comfortable headphones for focused study sessions. Charging cable included.',art:'headphones',color:'#eadfd5',created:5},
{id:'3',title:'Minimal desk lamp',category:'Dorm essentials',price:650,condition:'Like new',seller:'Sara',campus:'Adama Science & Technology University',description:'Sample listing. Compact adjustable lamp for a small dorm desk.',art:'lamp',color:'#e5def4',created:4},
{id:'4',title:'Introduction to Psychology',category:'Textbooks',price:500,condition:'Good',seller:'Noah',campus:'Addis Ababa University',description:'Sample listing. An introductory psychology textbook with highlighted chapters.',art:'book',color:'#f0decf',label:'PSYCHOLOGY',created:3},
{id:'5',title:'Compact mechanical keyboard',category:'Tech',price:1800,condition:'Like new',seller:'Hana',campus:'Adama Science & Technology University',description:'Sample listing. A small keyboard for your study setup. USB cable included.',art:'keyboard',color:'#dbe4f0',created:2},
{id:'6',title:'The little dorm plant',category:'Dorm essentials',price:300,condition:'Good',seller:'Abel',campus:'Addis Ababa University',description:'Sample listing. A decorative plant and ceramic pot for your desk.',art:'plant',color:'#dfe8d4',created:1}];
function load(key,fallback,valid){try{const v=JSON.parse(localStorage.getItem(key));return valid(v)?v:fallback}catch{return fallback}}
function Art({item}){if(item.image)return <img className="item-photo" src={item.image} alt={item.title} onError={e=>{e.currentTarget.style.display='none'}}/>;return <div className={'art '+item.art} aria-hidden="true">{item.art==='book'?<div className="book-object"><small>THE STUDENT EDITION</small><strong>{item.label||'YOUR NEXT<br/>CHAPTER'}</strong><div className="book-lines"/><span>LEARN. EXPLORE. GROW.</span></div>:item.art==='headphones'?<div className="headphone-object"><i/><b/><span/></div>:item.art==='lamp'?<div className="lamp-object"><i/><b/><span/></div>:item.art==='keyboard'?<div className="keyboard-object">{Array.from({length:40},(_,i)=><i key={i}/>)}</div>:item.art==='plant'?<div className="plant-object"><i/><i/><i/><b/></div>:<ShoppingBag size={80}/>}</div>}
function Modal({children,onClose,title}){const ref=useRef();useEffect(()=>{const prior=document.activeElement;const d=ref.current;d.showModal();return()=>{d.close();prior?.focus()}},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===e.currentTarget)onClose()}}><header className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></header>{children}</dialog>}
function App(){const [items,setItems]=useState(()=>load('cs-items-v1',seed,v=>Array.isArray(v)&&v.every(i=>i&&typeof i.id==='string'&&typeof i.title==='string'&&typeof i.price==='number')));const [saved,setSaved]=useState(()=>load('cs-saved-v1',[],v=>Array.isArray(v)&&v.every(x=>typeof x==='string')));const [query,setQuery]=useState('');const [category,setCategory]=useState('All finds');const [sort,setSort]=useState('newest');const [campus,setCampus]=useState('All campuses');const [onlySaved,setOnlySaved]=useState(false);const [modal,setModal]=useState(null);const [notice,setNotice]=useState('');const [image,setImage]=useState('');const [fileError,setFileError]=useState('');
useEffect(()=>{try{localStorage.setItem('cs-items-v1',JSON.stringify(items));localStorage.setItem('cs-saved-v1',JSON.stringify(saved))}catch{setNotice('Storage is full or unavailable. Your changes are temporary.')}},[items,saved]);
function toggle(id){setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id])}
const filtered=items.filter(i=>(category==='All finds'||i.category===category)&&(campus==='All campuses'||i.campus===campus)&&(!onlySaved||saved.includes(i.id))&&`${i.title} ${i.category}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:b.created-a.created);
function browse(){document.getElementById('marketplace').scrollIntoView({behavior:'smooth'})}
function reset(){setQuery('');setCategory('All finds');setCampus('All campuses');setOnlySaved(false)}
function publish(e){e.preventDefault();const f=new FormData(e.currentTarget);const price=Number(f.get('price'));if(!f.get('title').trim()||!f.get('seller').trim()||!f.get('description').trim()||!Number.isFinite(price)||price<=0)return;setItems(v=>[{id:crypto.randomUUID(),title:f.get('title').trim(),category:f.get('category'),price,condition:f.get('condition'),seller:f.get('seller').trim(),campus:f.get('campus'),description:f.get('description').trim(),email:f.get('email').trim(),image,art:'bag',color:'#e5def4',created:Date.now()},...v]);reset();setModal(null);setImage('');setNotice('Your listing is ready! It is saved in this browser.');browse()}
function upload(e){const file=e.target.files[0];setImage('');setFileError('');if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>1200000){setFileError('Choose a JPG, PNG, or WebP image under 1.2 MB.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>setImage(reader.result);reader.readAsDataURL(file)}
return <><nav className="topbar"><a href="#" className="logo"><span><Repeat2 size={23}/></span>campus<span className="logo-purple">swap</span><small>●</small></a><div className="nav-links"><button className={!onlySaved?'nav-active':''} onClick={()=>{setOnlySaved(false);browse()}}>Explore</button><button onClick={()=>{setOnlySaved(true);browse()}}>Saved finds <span className="saved-number">{saved.length}</span></button></div><button className="primary" onClick={()=>{setImage('');setModal('sell')}}><Plus size={18}/> Sell an item</button></nav>
<main><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> LESS SPENDING. MORE LIVING.</div><h1>Your campus.<br/>Your next <em>great find.</em></h1><p>Pre-loved textbooks, tech, and dorm essentials.<br className="desktop-break"/> Find what you need. Pass on what you don’t.</p><div className="hero-actions"><button className="primary" onClick={browse}>Explore the marketplace <ArrowUpRight size={19}/></button><span className="mini-note"><Leaf size={18}/> Good for your wallet.<br/>Better for the planet.</span></div><div className="hero-foot"><span className="avatars"><i>M</i><i>D</i><i>S</i></span><span>A little less new. A lot more you.</span></div></div><div className="hero-visual"><div className="orb"/><div className="floating-label label-top"><Leaf size={16}/> Give good things a second life</div><div className="hero-book"><small>YOUR NEXT CHAPTER</small><strong>Good<br/>things<br/><em>circulate.</em></strong><span>CAMPUSSWAP / STUDENT LIFE</span></div><div className="floating-label label-bottom"><span className="check-circle"><Check size={17}/></span><div>Big finds. Small prices.<small>Made for campus life</small></div></div><span className="sparkle">✳</span></div></section>
<div className="benefits"><span><Repeat2/> Buy & sell with students</span><span><Leaf/> Choose pre-loved</span><span><MapPin/> Find it on your campus</span></div>
<section id="marketplace"><div className="section-head"><div className="eyebrow">THE CAMPUS EDIT</div><h2>{onlySaved?'Your saved finds':'Fresh finds. Student prices.'}</h2><p>{onlySaved?'The things you love, all in one place.':'Something for your studies, your space, and everything in between.'}</p></div><div className="search-row"><div className="search"><Search size={20}/><input aria-label="Search listings" placeholder="Search textbooks, tech, and more…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" aria-label="Clear search" onClick={()=>setQuery('')}><X size={16}/></button>}</div><label className="campus"><MapPin size={17}/><select aria-label="Filter by campus" value={campus} onChange={e=>setCampus(e.target.value)}><option>All campuses</option><option>Addis Ababa University</option><option>Adama Science & Technology University</option></select></label></div><div className="filter-row"><div className="categories">{categories.map(([name,Icon])=><button key={name} className={category===name?'selected':''} aria-pressed={category===name} onClick={()=>setCategory(name)}><Icon size={17}/>{name}</button>)}</div><label className="sort"><SlidersHorizontal size={16}/><select aria-label="Sort listings" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div><div className="results"><span>{filtered.length} {filtered.length===1?'find':'finds'} to explore</span><span>ETB prices · Sample listings + your finds</span></div>
<div className="grid">{filtered.map(item=><article className="card" key={item.id}><div className="image-wrap" style={{background:item.color}}><button className="image-link" aria-label={'View '+item.title} onClick={()=>setModal(item)}><Art item={item}/></button><span className="condition">{item.condition}</span><button className={'favorite '+(saved.includes(item.id)?'is-saved':'')} aria-label={(saved.includes(item.id)?'Unsave ':'Save ')+item.title} aria-pressed={saved.includes(item.id)} onClick={()=>toggle(item.id)}><Heart size={19} fill={saved.includes(item.id)?'currentColor':'none'}/></button></div><div className="card-info"><div className="card-category">{item.category}</div><button className="item-title" onClick={()=>setModal(item)}>{item.title}</button><div className="card-price">{item.price.toLocaleString()} <small>ETB</small></div><div className="seller"><span className="seller-avatar">{item.seller[0]}</span><span>{item.seller}<small>{item.campus.replace('Science & Technology University','University')}</small></span><button aria-label={'View details for '+item.title} onClick={()=>setModal(item)}><ArrowUpRight size={18}/></button></div></div></article>)}</div>{!filtered.length&&<div className="empty"><ShoppingBag size={40}/><h3>No finds just yet.</h3><p>Try another search or add your own listing.</p><button className="primary" onClick={reset}>Reset filters</button></div>}
</section><section className="sell-banner"><div><div className="eyebrow">MAKE SPACE FOR WHAT’S NEXT</div><h2>Someone’s next favorite?<br/>It might be sitting on your shelf.</h2><p>Give your unused things a new chapter.</p></div><button className="primary" onClick={()=>{setImage('');setModal('sell')}}>List your first item <ArrowRight size={19}/></button></section><footer><a className="logo" href="#">campus<span className="logo-purple">swap</span></a><p>A student marketplace demo. Listings stay in your browser.</p><span>Built for the next chapter. ✳</span></footer></main>
{notice&&<div className="toast" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={17}/></button></div>}
{modal==='sell'&&<Modal title="Give it a new chapter." onClose={()=>setModal(null)}><p className="modal-intro">Add your find. Your listing will be saved on this browser.</p><form onSubmit={publish}><label>Item title<input name="title" required maxLength={90} placeholder="e.g. First-year calculus textbook"/></label><div className="form-row"><label>Category<select name="category">{categories.slice(1).map(([n])=><option key={n}>{n}</option>)}</select></label><label>Condition<select name="condition"><option>Like new</option><option>Good</option><option>Fair</option></select></label></div><div className="form-row"><label>Price (ETB)<input name="price" type="number" min="1" max="1000000" step="1" required placeholder="850"/></label><label>Your name<input name="seller" required maxLength={40} placeholder="First name"/></label></div><label>Campus<select name="campus"><option>Addis Ababa University</option><option>Adama Science & Technology University</option></select></label><label>Description<textarea name="description" required maxLength={700} rows={3} placeholder="Share the condition and what’s included."/></label><label>Contact email (optional)<input name="email" type="email" placeholder="you@example.com"/></label><label>Photo (optional)<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/><small>JPG, PNG or WebP · Under 1.2 MB</small></label>{fileError&&<p role="alert">{fileError}</p>}{image&&<img className="upload-preview" src={image} alt="Listing preview"/>}<button className="primary full" type="submit">Publish listing <ArrowUpRight size={18}/></button></form></Modal>}
{modal&&modal!=='sell'&&<Modal title="A closer look" onClose={()=>setModal(null)}><div className="detail-art" style={{background:modal.color}}><Art item={modal}/></div><div className="detail-meta">{modal.category} · {modal.condition}</div><h2 className="detail-title">{modal.title}</h2><div className="card-price">{modal.price.toLocaleString()} <small>ETB</small></div><p className="description">{modal.description}</p><p className="location"><MapPin size={16}/>{modal.campus}</p><div className="detail-seller"><span className="seller-avatar">{modal.seller[0]}</span>Listed by {modal.seller}</div><button className="secondary full" onClick={()=>toggle(modal.id)}><Heart size={18}/>{saved.includes(modal.id)?'Remove from saved':'Save this find'}</button>{modal.email?<a className="primary full" href={'mailto:'+modal.email+'?subject='+encodeURIComponent('CampusSwap: '+modal.title)}><Mail size={18}/> Email seller</a>:<p className="sample-note">This sample listing has no contact details. Add your own listing with an email to try contacting a seller.</p>}{!seed.some(s=>s.id===modal.id)&&<button className="delete-listing" onClick={()=>{if(window.confirm('Delete this listing?')){setItems(v=>v.filter(i=>i.id!==modal.id));setSaved(v=>v.filter(id=>id!==modal.id));setModal(null)}}}>Delete this listing</button>}</Modal>}
</>}
createRoot(document.getElementById('root')).render(<App/>);
